const usersData=[
    {
        id:Math.random(),name:'user1',email:"user1@gmail.com",age:25,gender:"femme",hometown:"kef"
      },
      {
        id:Math.random(),name:'user2',email:"user2@gmail.com",age:27,gender:"homme",hometown:"tunis"
      },
      {
        id:Math.random(),name:'user3',email:"user3@gmail.com",age:54,gender:"femme",hometown:"nabeul"
      },
      {
        id:Math.random(),name:'user4',email:"user4@gmail.com",age:37,gender:"homme",hometown:"kef"
      },
      {
        id:Math.random(),name:'user5',email:"user5@gmail.com",age:42,gender:"femme",hometown:"nabeul"
      },
      {
        id:Math.random(),name:'user6',email:"user6@gmail.com",age:18,gender:"femme",hometown:"tunis"
      },
      {
        id:Math.random(),name:'user7',email:"user7@gmail.com",age:30,gender:"homme",hometown:"kef"
      },
      {
        id:Math.random(),name:'user8',email:"user8@gmail.com",age:50,gender:"homme",hometown:"kef"
      },
      {
        id:Math.random(),name:'user9',email:"user9@gmail.com",age:47,gender:"homme",hometown:"tunis"
      },
      {
        id:Math.random(),name:'user10',email:"user10@gmail.com",age:26,gender:"femme",hometown:"tunis"
      },
      {
        id:Math.random(),name:'user11',email:"user11@gmail.com",age:22,gender:"femme",hometown:"nabeul"
      },
      {
        id:Math.random(),name:'user12',email:"user12@gmail.com",age:56,gender:"femme",hometown:"nabeul"
      },
      {
        id:Math.random(),name:'user13',email:"user13@gmail.com",age:20,gender:"homme",hometown:"kef"
      },
      {
        id:Math.random(),name:'user14',email:"user14@gmail.com",age:40,gender:"femme",hometown:"tunis"
      },
      {
        id:Math.random(),name:'user15',email:"user15@gmail.com",age:33,gender:"femme",hometown:"nabeul"
      }
]

export default usersData